// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEG3jmulk7zL8NEcjENbz89oA1ZOvOn00',
    appId: '1:81071435697:web:647926747a463592ee1790',
    messagingSenderId: '81071435697',
    projectId: 'gymzy-a5a04',
    authDomain: 'gymzy-a5a04.firebaseapp.com',
    storageBucket: 'gymzy-a5a04.firebasestorage.app',
    measurementId: 'G-5SYV94WK4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByZgZq0Pl_zuEXarcHwKtDNZbDWMnQUZI',
    appId: '1:81071435697:android:2c73fab8463d3f7cee1790',
    messagingSenderId: '81071435697',
    projectId: 'gymzy-a5a04',
    storageBucket: 'gymzy-a5a04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD__iqdxNLGGLaoMJR-isyYX2xMph54RyA',
    appId: '1:81071435697:ios:fdd48de4f107edbbee1790',
    messagingSenderId: '81071435697',
    projectId: 'gymzy-a5a04',
    storageBucket: 'gymzy-a5a04.firebasestorage.app',
    iosBundleId: 'com.example.aiChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD__iqdxNLGGLaoMJR-isyYX2xMph54RyA',
    appId: '1:81071435697:ios:fdd48de4f107edbbee1790',
    messagingSenderId: '81071435697',
    projectId: 'gymzy-a5a04',
    storageBucket: 'gymzy-a5a04.firebasestorage.app',
    iosBundleId: 'com.example.aiChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEG3jmulk7zL8NEcjENbz89oA1ZOvOn00',
    appId: '1:81071435697:web:bf31c835bacc3131ee1790',
    messagingSenderId: '81071435697',
    projectId: 'gymzy-a5a04',
    authDomain: 'gymzy-a5a04.firebaseapp.com',
    storageBucket: 'gymzy-a5a04.firebasestorage.app',
    measurementId: 'G-ZREP082GK9',
  );
}
